version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cross-server-discord-bot
    restart: unless-stopped
    environment:
      # Add your Discord token here or use a .env file
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=/
      - RATE_LIMIT_MESSAGES=5
      - RATE_LIMIT_PERIOD=60
      - LOG_LEVEL=INFO
      - LOG_FILE=bot.log
      - MAX_MESSAGE_LENGTH=2000
    volumes:
      # Optional: Mount logs directory to persist logs
      - ./logs:/app/logs
    # No ports needed for Discord bot
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge

# Optional: Add volume for persistent data
volumes:
  bot-logs:
    driver: local